#!/usr/bin/env ruby
# generated by org-babel-tangle

# [[file:~/src/genprog-ga/quad/parallel-test.org::*parallel%20execution%20times][block-1]]
  DEFAULT_CMDLINE = "--swap 0 --del 0 --mut 0.1 gcd.c "
  
  def run_and_package(cmdline, package)
    puts "#{package}: ../modify #{cmdline}"
    %x{../modify #{cmdline}}
    %x{rake package[#{package}]}
  end
  
  10.times do |n|
    # run with default options
    run_and_package(DEFAULT_CMDLINE, "default_#{n}")
    # run with parallel mutation
    run_and_package("--pll_mut " + DEFAULT_CMDLINE, "pll_mut_#{n}")
    # run with sub populations
    run_and_package("--sub_pops 2 " + DEFAULT_CMDLINE, "sub_pop_#{n}")
  end
# block-1 ends here
